defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: eve_corp_manager_development

test:
  <<: *defaults
  database: eve_corp_manager_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: eve_corp_manager
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
